name: Build and Publish to Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create rclone config file
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" | base64 -d > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf
          echo "Rclone config file created and decoded from base64"
      
      - name: Run MongoDB backup with rclone
        run: |
          docker run --rm \
            -v ~/.config/rclone/rclone.conf:/config/rclone/rclone.conf:ro \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e FILENAME="${{ secrets.FILENAME }}" \
            -e MONGODUMP_ARGS="${{ secrets.MONGODUMP_ARGS }}" \
            ${{ secrets.IMAGE_NAME }}