name: Build and Publish to Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run MongoDB backup with rclone
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          docker run --rm \
            -e RCLONE_CONFIG=$RCLONE_CONFIG
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e FILENAME="${{ secrets.FILENAME }}" \
            -e MONGODUMP_ARGS="${{ secrets.MONGODUMP_ARGS }}" \
            ${{ secrets.IMAGE_NAME }}
